apiVersion: v1
kind: Service
metadata:
  name: agent-framework
  namespace: agent-framework
  labels:
    app: agent-framework
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: health
  selector:
    app: agent-framework

