apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: agent-framework
  labels:
    app: traffic-generator
    component: load-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
        component: load-testing
    spec:
      containers:
      - name: traffic-generator
        image: traffic-generator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: metrics
          protocol: TCP
        args:
        - "-target=http://agent-framework:8080"
        - "-pattern=gradual"
        - "-duration=10m"
        - "-base-load=10"
        - "-peak-load=100"
        - "-metrics-port=8081"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: traffic-generator
  namespace: agent-framework
  labels:
    app: traffic-generator
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: metrics
  selector:
    app: traffic-generator

