logging:
  level: info
  format: text
  output: stdout

agent:
  default_agent: "real-ai"

plugins:
  - name: "real-prometheus"
    type: "prometheus"
    config:
      url: "http://localhost:9090"
      interval: "10s"
      queries: 
        - "up"
        - "prometheus_tsdb_head_samples"
        - "prometheus_tsdb_head_series"
        - "prometheus_http_requests_total"
        - "go_memstats_alloc_bytes"
        - "go_gc_duration_seconds"
  
  - name: "real-analyzer"
    type: "anomaly"
    config:
      threshold: 2.0
  
  - name: "real-logger"
    type: "logger"
    config:
      level: "info"
  
  - name: "real-ai"
    type: "ai"
    config:
      model: "gpt-4"
      max_tokens: 500
      temperature: 0.7
